// ⚠️ AUTOGENERATED ⚠️ AUTOGENERATED ⚠️ AUTOGENERATED ⚠️
// This file was automatically generated by `tools/gen-ts-glue.ts`. Do not modify directly if you want to keep your changes.
export * from "./src/WebpackPlugin";
import defaultExport from "./src/WebpackPlugin";
export default defaultExport;
